# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M03Oji1sxZXwA1WTpKijNLdJLDohpvHp
"""

import requests
import pandas as pd
from datetime import datetime, timedelta

# 1
def get_weather_data():
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        # Саме цей сайт видає інфу через вказані широту і довготу
        'latitude': 50.4547,
        'longitude': 30.5238,
        'hourly': 'temperature_2m,windspeed_10m',
        'timezone': 'auto',
        'forecast_days': 7
    }
    response = requests.get(url, params=params)
    return response.json()

# 2
def process_weather_data(json_data):
    hourly = json_data['hourly']
    df = pd.DataFrame({
        'time': hourly['time'],
        'temperature': hourly['temperature_2m'],
        'windspeed': hourly['windspeed_10m']
    })
    df['time'] = pd.to_datetime(df['time'])
    return df

# 3
def perform_eda(df):
    three_days = df[df['time'] <= datetime.now() + timedelta(days=3)]
    temp_min = three_days['temperature'].min()
    temp_max = three_days['temperature'].max()
    temp_mean = three_days['temperature'].mean()

    avg_wind = df['windspeed'].mean()
    wind_hours = df[df['windspeed'] > avg_wind].shape[0]

    return {
        'temp_min': temp_min,
        'temp_max': temp_max,
        'temp_mean': temp_mean,
        'wind_hours': wind_hours,
        'avg_wind': avg_wind
    }

weather_json = get_weather_data()
weather_df = process_weather_data(weather_json)
analysis_results = perform_eda(weather_df)

print(weather_df.head()) #щоб подивитися як виглядають дані у dataframe
print()
print(f"Мінімальна температура: {analysis_results['temp_min']:.1f}°C")
print(f"Максимальна температура: {analysis_results['temp_max']:.1f}°C")
print(f"Середня температура: {analysis_results['temp_mean']:.1f}°C")
print(f"Годин з вітром більше середньої швидкості ({analysis_results['avg_wind']:.1f} км/год): {analysis_results['wind_hours']}")